version: "3"

services:
  #
  web_service:
    container_name: web_container
    image: web_image:5.3
    build: ./web/
    depends_on:
      - mysql_service
    restart: always
    environment:
      TZ: "Asia/Tokyo"
    volumes:
      - ./html:/var/www
    ports:
      - 8080:80
    working_dir: /var
  #
  mysql_service:
    container_name: mysql_container
    image: mysql_image:5.6
    build: ./mysql/
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: YUKKURI_DATABASE
      MYSQL_USER: YUKKURI_USER
      MYSQL_PASSWORD: YUKKURI_PASSWORD
      TZ: "Asia/Tokyo"
    volumes:
      - ./mysql/database:/var/lib/mysql
    ports:
      - "3307:3306"
