DROP DATABASE IF EXISTS `YUKKURRI_DATABASE`;
CREATE DATABASE `YUKKURI_DATABASE` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;


GRANT ALL PRIVILEGES ON *.* TO `YUKKURI_USER`@`%` IDENTIFIED BY 'YUKKURI_PASSWORD';
GRANT ALL ON `YUKKURI_DATABASE`.* to `YUKKURI_USER`@`%`;


USE `YUKKURI_DATABASE`;

DROP TABLE IF EXISTS `YUKKURI_TABLE`;
CREATE TABLE `YUKKURI_TABLE` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `namae` varchar(64) COLLATE utf8_unicode_ci DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY  (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=17 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

INSERT INTO `YUKKURI_TABLE`(`namae`) VALUES
  ('れいむ'),
  ('まりさ'),
  ('ありす'),
  ('みょん'),
  ('ぱちゅりー'),
  ('ちぇん');
